---

- name: Ensure /opt/oulib/aws/bin exists
  file:
    path: /opt/oulib/aws/bin
    state: directory
    mode: 0755
    owner: root
    group: wheel

- name: Copy helper scripts to /opt/oulib/aws/bin
  copy:
    src: "{{ item }}"
    dest: /opt/oulib/aws/bin
    mode: 0755
    owner: root
    group: wheel
  with_items:
    - ec2_get_account_id.sh
    - ec2_get_arn.sh
    - ec2_get_region.sh
  tags: assets
