---
- name: Pip build dependencies are present
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - gcc
  - python-devel

- name: Verify latest pip and aws-cli is installed
  pip:
    name: "{{ item }}"
    state: present
  with_items:
  - pip
  - awscli

- name: Pip build dependencies are absent
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
  - gcc
  - python-devel

- name: Ensure /opt/oulib/aws/bin exists
  file:
    path: /opt/oulib/aws/bin
    state: directory
    mode: 0755
    owner: root
    group: wheel
    recurse: yes

- name: Copy helper scripts to /opt/oulib/aws/bin
  copy:
    src: "{{ item }}"
    dest: /opt/oulib/aws/bin
    mode: 0755
    owner: root
    group: root
  with_items:
    - ec2_get_account_id.sh
    - ec2_get_arn.sh
    - ec2_get_region.sh
  tags: assets
