---
- include: setup.yml
  sudo: yes
  tags:
  - ec2
  - vagrant
  - vsphere
- include: vsphere.yml
  when: (ansible_virtualization_type == "VMware") and (ansible_virtualization_role == "guest")
  sudo: yes
  tags:
  - vsphere
- include: ec2.yml
  when: ("amazon" in ansible_product_version) and (ansible_virtualization_type == "xen") and (ansible_virtualization_role == "guest")
  sudo: yes
  tags:
  - ec2
