---
- include: setup.yml
  sudo: yes
  tags:
  - ec2
  - virtualbox
  - vsphere
- include: yum.yml
  sudo: yes
  tags:
  - ec2
  - virtualbox
  - vsphere
- include: users.yml
  sudo: yes
  tags:
  - ec2
  - virtualbox
  - vsphere
- include: ssh.yml
  sudo: yes
  tags:
  - ec2
  - virtualbox
  - vsphere
- include: ec2.yml
  when: ("amazon" in ansible_product_version) and (ansible_virtualization_type == "xen") and (ansible_virtualization_role == "guest")
  sudo: yes
  tags:
  - ec2
- include: virtualbox.yml
  when: (ansible_virtualization_type == "virtualbox") and (ansible_virtualization_role == "guest")
  sudo: yes
  tags:
  - virtualbox
- include: vsphere.yml
  when: (ansible_virtualization_type == "VMware") and (ansible_virtualization_role == "guest")
  sudo: yes
  tags:
  - vsphere
