---
- include: setup.yml
  sudo: yes
- include: yum.yml
  sudo: yes
- include: ec2.yml
  when: ("amazon" in ansible_product_version) and (ansible_virtualization_type == "xen") and (ansible_virtualization_role == "guest")
  sudo: yes
  tags:
  - ec2
- include: virtualbox.yml
  when: (ansible_virtualization_type == "virtualbox") and (ansible_virtualization_role == "guest")
  sudo: yes
  tags:
  - virtualbox
- include: vmware.yml
  when: (ansible_virtualization_type == "VMware") and (ansible_virtualization_role == "guest")
  sudo: yes
  tags:
  - vmware
