---
- include: setup.yml
  sudo: yes
  tags:
  - aws
  - vagrant
  - vsphere
- include: vsphere.yml
  when: (ansible_virtualization_type == "VMware") and (ansible_virtualization_role == "guest")
  sudo: yes
  tags:
  - vsphere
