---
- name: Metal-specific packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - iptables-services
- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: yes
- name: Apply iptables template
  template:
    src: iptables.j2
    dest: /etc/sysconfig/iptables
    mode: 0600
    owner: root
    group: root
- name: Restart iptables, run on boot
  service:
    name: iptables
    state: restarted
    enabled: yes
- name: Set hostname
  hostname: name="{{ server_name }}"
