---
- name: Metal- or VMWare-specific packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - iptables-services
- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: yes
- name: Apply iptables template
  template:
    src: iptables.j2
    dest: /etc/sysconfig/iptables
    mode: 0600
    owner: root
    group: root
- name: Restart iptables, run on boot
  service:
    name: iptables
    state: restarted
    enabled: yes
- name: Remove any previous /etc/hosts entries with this name
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ server_name }}"
    state: absent
    backup: yes
- name: Remove any previous /etc/hosts entries with this ip
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ server_ip }}"
    state: absent
    backup: yes
- name: Set /etc/hosts with current name and ip
  lineinfile:
    dest: /etc/hosts
    line: "{{ server_ip }} {{ server_name }}"
- name: Set hostname using ansible module
  hostname:
    name: "{{ server_name }}"
- name: Set hostname using hostnamectl
  shell: hostnamectl set-hostname "{{ server_name }}"
