---

- name: Check Timezone
  shell: >
    set -o pipefail && timedatectl status | grep Time\ zone: | cut -d ':' -f 2 | cut -d '(' -f 1 | xargs
  check_mode: no
  register: timezone
  changed_when: timezone.stdout != server_timezone
  notify:
  - Set timezone

- name: Comment out IPv6 loopback entry in /etc/hosts.
  replace:
    dest: /etc/hosts
    regexp: '^((::1)(.+))$'
    replace: '#\1'
    backup: yes
    unsafe_writes: "{{ 'yes' if is_docker_guest else 'no' }}"
  when:
    - centos7_ipv6_disable

- name: Copy IPv6 sysctl Config
  copy:
    src: disableipv6.conf
    dest: /etc/sysctl.d/disableipv6.conf
    owner: root
    group: root
    mode: 0644
  when:
    - centos7_ipv6_disable

- name: Immediately disable disble IPv6 on all interfaces
  command: sysctl -w net.ipv6.conf.all.disable_ipv6=1
  when:
    - centos7_ipv6_disable

- name: Apply sysctl
  command: sysctl -p
  when:
    - centos7_ipv6_disable

