---
- name: Check Timezone
  shell: >
    timedatectl status | grep Timezone: | cut -d ':' -f 2 | cut -d '(' -f 1 | xargs
  always_run: yes
  register: timezone
  changed_when: timezone.stdout != "{{ server_timezone }}"
  notify:
  - Set timezone
- name: Clean yum.
  command: yum -y clean all
- name: Packages for yum.
  yum: name={{ item }} state=latest update_cache=yes
  with_items:
  - yum
  - yum-cron
  - deltarpm
  - epel-release
  - yum-priorities
  retries: 1
- name: yum-cron set for security updates
  lineinfile: "dest=/etc/yum/yum-cron.conf state=present regexp='^update_cmd = default$' line='update_cmd = security'"
- name: yum-cron apply updates
  lineinfile: "dest=/etc/yum/yum-cron.conf state=present regexp='^apply_updates = no$' line='apply_updates = yes'"
- name: Start yum-cron on boot
  service:
    name: yum-cron
    state: started
    enabled: yes
- name: CentOS-Base has priority
  ini_file:
    dest: /etc/yum.repos.d/CentOS-Base.repo
    section: base
    option: priority
    value: 1
    backup: yes
- name: CentOS-Updates has priority
  ini_file:
    dest: /etc/yum.repos.d/CentOS-Base.repo
    section: updates
    option: priority
    value: 1
    backup: yes
- name: Utility packages.
  yum: name={{ item }} state=present
  with_items:
  - python-pip
  - nload
  - htop
  - sysstat
  - psmisc
  - iotop
  - policycoreutils-python
  - git
  - wget
  - curl
  - tree
  - emacs-nox
  - vim
  - ack
  - tmux
  - screen
  - unzip
  - shadow-utils
- name: Security updates
  command: yum -y update --security
- name: Ensure /usr/local belongs to root:wheel 0775
  file: path=/usr/local state=directory mode=0775 owner=root group=wheel recurse=yes
- name: Ensure /opt belongs to root:wheel 0775
  file: path=/opt state=directory mode=0775 owner=root group=wheel recurse=yes
- include: user.yml
- name: Add vagrant user
  user: name=vagrant state=present
- name: Add vagrant user to wheel group
  command: usermod -a -G wheel vagrant
- name: Give vagrant user passwordless sudo
  lineinfile: "dest=/etc/sudoers line='vagrant ALL=(ALL) NOPASSWD: ALL' validate='visudo -cf %s'"
- name: Disable requiretty for sudo
  lineinfile: "dest=/etc/sudoers state=present regexp='^Defaults    requiretty$' line='#Defaults    requiretty' validate='visudo -cf %s'"
- name: Ensure vagrant user has the /vagrant directory
  file: path=/vagrant state=directory mode=0775 owner=vagrant group=wheel
- include: ssh.yml
