---

- name: Check Timezone
  shell: >
    timedatectl status | grep Timezone: | cut -d ':' -f 2 | cut -d '(' -f 1 | xargs
  always_run: yes
  register: timezone
  changed_when: timezone.stdout != "{{ server_timezone }}"
  notify:
  - Set timezone

- name: Create swap file
  command: >
    dd if=/dev/zero of={{ centos7_swap.file_path }} bs=1024 count={{ centos7_swap.file_size }}
  args:
    creates: "{{ centos7_swap.file_path }}"
  when: ((centos7_swap is defined) and (centos7_swap is not none))

- name: Change swap file permissions
  file:
    path: "{{ centos7_swap.file_path }}"
    owner: root
    group: root
    mode: 0600
  when: ((centos7_swap is defined) and (centos7_swap is not none))

- name: Check swap file
  command: >
    grep '{{ centos7_swap.file_path }}' /proc/swaps
  register: swapfile_test
  when: ((centos7_swap is defined) and (centos7_swap is not none))
  ignore_errors: yes

- name: Make swap file
  command: >
    mkswap {{ centos7_swap.file_path }}
  when: ((centos7_swap is defined) and (centos7_swap is not none) and (swapfile_test.rc != 0))

- name: Use swap file
  command: >
    swapon {{ centos7_swap.file_path }}
  when: ((centos7_swap is defined) and (centos7_swap is not none) and (swapfile_test.rc != 0))

- name: Write swap entry in fstab
  mount:
    name: swap
    src: "{{ centos7_swap.file_path }}"
    fstype: swap
    opts: defaults
    dump: 0
    passno: 0
    state: present
  when: ((centos7_swap is defined) and (centos7_swap is not none))

- name: Install shell profile config
  copy:
    src: "{{ item }}"
    dest: /etc/profile.d/
    owner: root
    group: wheel
    mode: 0644
  with_items:
    - colorprompt.sh
    - editor.sh
  tags: assets

- name: Comment out IPv6 loopback entry in /etc/hosts.
  replace:
    dest: /etc/hosts
    regexp: '^((::1)(.+))$'
    replace: '#\1'
    backup: yes

- name: Copy IPv6 sysctl Config
  copy:
    src: disableipv6.conf
    dest: /etc/sysctl.d/disableipv6.conf
    owner: root
    group: root
    mode: 0644

- name: Immediately disable disble IPv6 on all interfaces
  command: sysctl -w net.ipv6.conf.all.disable_ipv6=1

- name: Apply sysctl
  command: sysctl -p
