---

- name: Check Timezone
  shell: >
    timedatectl status | grep Timezone: | cut -d ':' -f 2 | cut -d '(' -f 1 | xargs
  always_run: yes
  register: timezone
  changed_when: timezone.stdout != "{{ server_timezone }}"
  notify:
  - Set timezone

- name: Ensure /usr/local belongs to root:wheel 0775
  file:
    path: /usr/local
    mode: 0775
    owner: root
    group: wheel
    state: directory
    recurse: yes

- name: Ensure /opt belongs to root:wheel 0775
  file:
    path: /opt
    state: directory
    mode: 0775
    owner: root
    group: wheel
    recurse: yes

- name: Install shell profile config
  copy:
    src: "{{ item }}"
    dest: /etc/profile.d/
    owner: root
    group: wheel
    mode: 0644
  with_items:
    - colorprompt.sh
    - editor.sh

- name: Comment out IPv6 loopback entry in /etc/hosts.
  replace:
    dest: /etc/hosts
    regexp: '^((::1)(.+))$'
    replace: '#\1'
    backup: yes

- name: Copy IPv6 sysctl Config
  copy:
    src: disableipv6.conf
    dest: /etc/sysctl.d/disableipv6.conf
    owner: root
    group: root
    mode: 0644

- name: Apply sysctl
  command: sysctl -p
