---
- name: Check Timezone
  shell: >
    timedatectl status | grep Timezone: | cut -d ':' -f 2 | cut -d '(' -f 1 | xargs
  always_run: yes
  register: timezone
  changed_when: timezone.stdout != "{{ server_timezone }}"
  notify:
  - Set timezone
- name: Ensure /usr/local belongs to root:wheel 0775
  file: path=/usr/local state=directory mode=0775 owner=root group=wheel recurse=yes
- name: Ensure /opt belongs to root:wheel 0775
  file: path=/opt state=directory mode=0775 owner=root group=wheel recurse=yes
