---
- name: user
  user: name={{ user_name }} groups={{ user_groups }} append=yes
  register: user
- name: ssh keys
  authorized_key:
    user: "{{ user_name }}"
    key: "{{ user_pubkey }}"
    state: present
    exclusive: yes
