---
- name: Yum packages for building dynamic kernel modules.
  yum: name={{ item }} state=present
  with_items:
    - bzip2
    - dkms
    - gcc
    - make
- name: Identify installed kernels
  shell: >
    rpm -qa kernel | cut -d '-' -f 2,3
  register: get_installed_kernel_versions
- name: Identify latest installed VirtualBox Guest Additions source
  shell: >
    find /usr/src -maxdepth 1 -name "vboxguest-*" -exec basename "{}" \; | sort | tail -1 | cut -d '-' -f 2
  register: get_vboxguest_version
- name: Yum devel package for each installed kernel
  yum:
    name: "kernel-devel-{{ item }}"
    state: present
  with_items: "{{ get_installed_kernel_versions.stdout_lines }}"
- name: Yum headers package for each installed kernel
  yum:
    name: "kernel-headers-{{ item }}"
    state: present
  with_items: "{{ get_installed_kernel_versions.stdout_lines }}"
- name: Start DKMS on boot
  service:
    name: dkms
    state: started
    enabled: yes
- name: Get checksum for VBoxGuestAdditions
  uri:
    url: "http://download.virtualbox.org/virtualbox/{{ get_vboxguest_version.stdout }}/MD5SUMS"
    return_content: yes
  register: vbox_md5sums
#- name: Get VBoxGuestAdditions
#  get_url:
#    url: "http://download.virtualbox.org/virtualbox/{{ get_vboxguest_version.stdout }}/VBoxGuestAdditions_{{ get_vboxguest_version.stdout }}.iso"
#    dest: "/vagrant/VBoxGuestAdditions_{{ get_vboxguest_version.stdout }}.iso"
#    checksum: "md5:{{ vbox_md5sums.content[0:32] }}"
- name: Mount VBoxGuestAdditions ISO
  mount:
    name: /media/VBoxGuestAdditions
    src: "/vagrant/VBoxGuestAdditions_{{ get_vboxguest_version.stdout }}.iso"
    fstype: iso9660
    opts: loop
    state: mounted
- name: Install VBoxGuestAdditions with DKMS support
  command: >
    /media/VBoxGuestAdditions/VBoxLinuxAdditions.run
- name: Unmount VBoxGuestAdditions ISO
  mount:
    name: /media/VBoxGuestAdditions
    state: unmounted
- name: DKMS autoinstall
  command: dkms autoinstall
