---
- name: Build chain for VirtualBox Guest Additions.
  yum: name={{ item }} state=present
  with_items:
    - bzip2
    - dkms
    - gcc
    - make
    - yum-plugin-versionlock
- name: Lock kernel version
  command: yum versionlock kernel
- name: Identify installed kernels
  shell: >
    rpm -qa kernel | cut -d '-' -f 2,3
  register: get_installed_kernel_versions
- name: Identify latest installed VirtualBox Guest Additions source
  shell: >
    find /usr/src -maxdepth 1 -name "vboxguest-*" -exec basename "{}" \; | sort | tail -1 | cut -d '-' -f 2
  register: get_vboxguest_version
- name: Identify path for latest Guest Additions Executable
  shell: >
    find /opt/ -wholename "/opt/VBoxGuestAdditions-*/init/vboxadd" | sort | tail -1
  register: get_vboxadd
- name: Yum devel package for each installed kernel
  yum:
    name: "kernel-devel-{{ item }}"
    state: present
  with_items: "{{ get_installed_kernel_versions.stdout_lines }}"
  ignore_errors: yes
- name: Yum headers package for each installed kernel
  yum:
    name: "kernel-headers-{{ item }}"
    state: present
  with_items: "{{ get_installed_kernel_versions.stdout_lines }}"
  ignore_errors: yes
- name: Start DKMS on boot
  service:
    name: dkms
    state: started
    enabled: yes
- name: DKMS add vboxguest
  command: >
    dkms add -m vboxguest -v {{ get_vboxguest_version.stdout }} --all
  ignore_errors: yes
- name: Install vboxadd
  command: >
    {{ get_vboxadd.stdout }} setup
- name: Install rc.local script to recover from vagrant/vbox guest additions issues on boot
  copy:
    src: virtualbox_rc.local
    dest: /etc/rc.d/rc.local
    owner: root
    group: wheel
    mode: 0755
