---
- name: VMWware-specific packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - open-vm-tools

- name: Get ifcfg path
  shell: >
    find /etc/sysconfig/network-scripts -type f -name "ifcfg-*" | sort | head -1
  register: get_ifcfg_path
  check_mode: no

- name: Start VMWare Tools on boot
  service:
    name: vmtoolsd
    state: started
    enabled: yes

- name: Configure NIC
  lineinfile:
    dest: "{{ get_ifcfg_path.stdout }}"
    state: present
    regexp: '^IPADDR=(.+)'
    line: 'IPADDR="{{ server_ip }}"'
