---

- name: Yum update
  yum:
    name: "*"
    state: present
    update_cache: yes

- name: Packages for yum.
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - deltarpm
    - epel-release
    - yum
    - yum-cron
    - yum-priorities
    - yum-plugin-versionlock

- name: Update SELinux yum packages to latest
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux-python
    - policycoreutils
    - policycoreutils-python
    - polkit
    - selinux-policy
    - selinux-policy-targeted
  tags: selinux

- name: yum-cron apply updates
  lineinfile: "dest=/etc/yum/yum-cron.conf state=present regexp='^apply_updates = no$' line='apply_updates = yes'"

- name: Start yum-cron on boot
  service:
    name: yum-cron
    state: started
    enabled: yes

- name: CentOS-Base has priority
  ini_file:
    dest: /etc/yum.repos.d/CentOS-Base.repo
    section: base
    option: priority
    value: 1
    backup: yes
  when: ((ansible_distribution == "CentOS")  and (ansible_distribution_major_version == "7"))


- name: CentOS-Updates has priority
  ini_file:
    dest: /etc/yum.repos.d/CentOS-Base.repo
    section: updates
    option: priority
    value: 1
    backup: yes
  when: ((ansible_distribution == "CentOS")  and (ansible_distribution_major_version == "7"))

- name: Utility packages.
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - ack
  - bind-utils
  - bash-completion
  - curl
  - emacs-nox
  - git
  - htop
  - iotop
  - jq
  - nload
  - psmisc
  - python-pip
  - screen
  - shadow-utils
  - sysstat
  - tmux
  - tree
  - unzip
  - vim
  - wget
