---

- name: Yum update
  yum:
    name: "*"
    state: latest
    update_cache: yes

- name: Packages for yum.
  yum:
    name:
      - deltarpm
      - epel-release
      - yum
      - yum-priorities
      - yum-plugin-versionlock
    state: present

- name: Update SELinux yum packages to latest
  yum:
    name:
      - libselinux-python
      - policycoreutils
      - policycoreutils-python
      - polkit
      - selinux-policy
      - selinux-policy-targeted
      - setroubleshoot-plugins.noarch
      - setroubleshoot.x86_64
    state: present
  tags: selinux

- name: CentOS-Base has priority
  ini_file:
    dest: /etc/yum.repos.d/CentOS-Base.repo
    section: base
    option: priority
    value: "1"
    backup: yes
  when: ((ansible_distribution == "CentOS")  and (ansible_distribution_major_version == "7"))


- name: CentOS-Updates has priority
  ini_file:
    dest: /etc/yum.repos.d/CentOS-Base.repo
    section: updates
    option: priority
    value: "1"
    backup: yes
  when: ((ansible_distribution == "CentOS")  and (ansible_distribution_major_version == "7"))

- name: Utility packages.
  yum:
    name:
      - ack
      - bind-utils
      - bash-completion
      - curl
      - emacs-nox
      - git
      - htop
      - iotop
      - jq
      - lsof
      - nload
      - psmisc
      - screen
      - shadow-utils
      - sysstat
      - tmux
      - tree
      - unzip
      - vim
      - wget
    state: present
